export const gray = "#F7FAFC";
export const black = "#000000";
export const white = "#FFFFFF";
export const darkGray = "#A3A8B0";
export const textColor = white;
export const backgroundColor = "#1A365D";
export const buttonHeight = "48px";
export const buttonWidth = "180px";
export const formLabelWidth = "200px";
export const colors = [
  "#e6194b",
  "#3cb44b",
  "#ffe119",
  "#4363d8",
  "#f58231",
  "#911eb4",
  "#46f0f0",
  "#f032e6",
  "#bcf60c",
  "#fabebe",
  "#008080",
  "#e6beff",
  "#9a6324",
  "#fffac8",
  "#800000",
  "#aaffc3",
  "#808000",
  "#ffd8b1",
  "#000075",
  "#808080",
  "#000000",
];
export const nb_to_show = 5;
export const categories = [
  //quickdraw classes
  "sea_turtle",
  "violin",
  "fan",
  "teapot",
  "horse",
  "sink",
  "dog",
  "cactus",
  "hat",
  "pineapple",
  "zebra",
  "shoe",
  "rhinoceros",
  "skateboard",
  "hot-air_balloon",
  "bandage",
  "spider",
  "scorpion",
  "kangaroo",
  "guitar",
  "ant",
  "hammer",
  "rabbit",
  "alarm_clock",
  "skyscraper",
  "couch",
  "chair",
  "tree",
  "lobster",
  "pickup_truck",
  "cat",
  "bread",
  "megaphone",
  "wine bottle",
  "spoon",
  "cruise ship",
  "airplane",
  "map",
  "snail",
  "giraffe",
  "owl",
  "teddy_bear",
  "motorcycle",
  "axe",
  "dolphin",
  "crab",
  "sheep",
  "apple",
  "eiffel tower",
  "butterfly",
  "bear",
  "cup",
  "candle",
  "hamburger",
  "pig",
  "hedgehog",
  "saw",
  "bus",
  "moon",
  "raccoon",
  "soccer ball",
  "bench",
  "fish",
  "parrot",
  "penguin",
  "bee",
  "feather",
  "knife",
  "shark",
  "duck",
  "chandelier",
  "eyeglasses",
  "helicopter",
  "frog",
  "castle",
  "sailboat",
  "church",
  "snake",
  "elephant",
  "bicycle",
  "camel",
  "beach",
  "bat",
  "fire_hydrant",
  "banana",
  "monkey",
  "windmill",
  "mouse",
  "squirrel",
  "pizza",
  "lion",
  "door",
  "car",
  "cow",
  "scissors",
  "campfire",
  "flower",
  "train",
  "cake",
  "swan",
  "mountain",
  "umbrella",
  "rifle",
  "saxophone",
  "palm tree",
  "hurricane",
  "crocodilian",
  "tiger",
  "lighthouse",
  "mushroom",
];
