export const gray = "#F7FAFC";
export const black = "#000000";
export const white = "#FFFFFF";
export const darkGray = "#A3A8B0";
export const textColor = white;
export const backgroundColor = "#1A365D";
export const buttonHeight = "48px";
export const buttonWidth = "180px";
export const formLabelWidth = "200px";
export const custom_sketch_class = "My Custom Sketch"; // update python constant if modify
export const colors = [
  "#e6194b",
  "#3cb44b",
  "#ffe119",
  "#4363d8",
  "#f58231",
  "#911eb4",
  "#46f0f0",
  "#f032e6",
  "#bcf60c",
  "#fabebe",
  "#008080",
  "#e6beff",
  "#9a6324",
  "#fffac8",
  "#800000",
  "#aaffc3",
  "#808000",
  "#ffd8b1",
  "#000075",
  "#808080",
  "#000000",
];
export const nb_to_show = 5;
export const categories = [
  "airplane",
  "alarm_clock",
  "ant",
  "apple",
  "axe",
  "banana",
  "bandage",
  "bat",
  "beach",
  "bear",
  "bee",
  "bench",
  "bicycle",
  "bread",
  "bus",
  "butterfly",
  "cactus",
  "cake",
  "camel",
  "campfire",
  "candle",
  "car",
  "castle",
  "cat",
  "chair",
  "chandelier",
  "church",
  "couch",
  "cow",
  "crab",
  "crocodilian",
  "cruise ship",
  "cup",
  "dog",
  "dolphin",
  "door",
  "duck",
  "eiffel tower",
  "elephant",
  "eyeglasses",
  "fan",
  "feather",
  "fire_hydrant",
  "fish",
  "flower",
  "frog",
  "giraffe",
  "guitar",
  "hamburger",
  "hammer",
  "hat",
  "hedgehog",
  "helicopter",
  "horse",
  "hot-air_balloon",
  "hurricane",
  "kangaroo",
  "knife",
  "lighthouse",
  "lion",
  "lobster",
  "map",
  "megaphone",
  "monkey",
  "moon",
  "motorcycle",
  "mountain",
  "mouse",
  "mushroom",
  "owl",
  "palm tree",
  "parrot",
  "penguin",
  "pickup_truck",
  "pig",
  "pineapple",
  "pizza",
  "rabbit",
  "raccoon",
  "rhinoceros",
  "rifle",
  "sailboat",
  "saw",
  "saxophone",
  "scissors",
  "scorpion",
  "sea_turtle",
  "shark",
  "sheep",
  "shoe",
  "sink",
  "skateboard",
  "skyscraper",
  "snail",
  "snake",
  "soccer ball",
  "spider",
  "spoon",
  "squirrel",
  "swan",
  "teapot",
  "teddy_bear",
  "tiger",
  "train",
  "tree",
  "umbrella",
  "violin",
  "windmill",
  "wine bottle",
  "zebra",
];
