version: "3"

services:

  proxy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - /io:/app/io

  frontend:
    build:
      context: web_app/sketchy
      dockerfile: Dockerfile
    ports:
      - 3000:3000
